### ISSUE TITLE
em dash, en dash

### ISSUE THREAD

**Issue by kwaaui** [klepas/open-baskerville#11]
Hi, including "em dash" and "en dash" would be a great improvement!

**Comment by codingisacopingstrategy** [comment]
Good point, a basic em and en dash are now in trunk. Will upload a package as soon as we have had the chance to tweak these new glyphs copied over from Century Catalogue.

**Comment by codingisacopingstrategy** [comment]
The latest release contains em and en dash. They might be further refined (see issue #14 ), but I’m closing this for now.
