### ISSUE TITLE
Design ç and Ç (cedille)

### ISSUE THREAD

**Issue by codingisacopingstrategy** [klepas/open-baskerville#3]
Christopher Adams notes, to make the font ideographically complete for Western Latin (which, I suppose, is our main target now), we need: 

U+00c7 (Ç), U+00e7 (ç)

In fact, one would only need to make a cedille accent glyph: the two cedille glyphs can then be created by juxtaposition.

_Meta_

I wrote the ticket as a phrase that would fit in a ‘to do’ list—this is what would be the easiest if we want to be pulling these tickets in to the site. A heading CONTRIBUTE, and underneath little links like: ‘design the cedille’, ‘make a template for the italic’, ‘sketch the body weight’ etc.

You’d have to write a little sinatra / flask app for that that generates a javascript since we’re using static hosting on gh-pages.

So uhm, moving the tickets to Gh. Well, obviously it’s more barebones than Lighthouse. I’d miss the opportunity to upload pictures, the ability to plan milestones and the ability to leave messages.

But the large and obvious advantage is that it’s integrated with the code hosting, and people need only one account. No login required. I suppose that does make it a good idea.

**Comment by klepas** [comment]
Yup, agreed on all points. As we chatted on Skype I’mn going to move things over to GitHub issues here and then will see about pulling out five or so into the OB page on klepas.org.

**Comment by codingisacopingstrategy** [comment]
@ichosis , since you already created other hanging bits, would you feel like taking on the cedille?

**Comment by grzegorzrolek** [comment]
I’d need to do some research first, so this could take time. But, hell, why not?

**Comment by codingisacopingstrategy** [comment]
Awesome! And good and quick rarely go together :) Keep us posted!

**Comment by codingisacopingstrategy** [comment]
Fixed in ba9216425574a21478eaff002a897cd4b0aec1cc
